// Generated by scripts/build-images.cjs — do not edit by hand.
// Source of truth: docs/assets/image-manifest.json
// Regenerate with: npm run build:images

import type { ImageAsset } from '@/content/images';

export const GENERATED_IMAGES: ImageAsset[] = [
  {
    "file": "/images/groups/cohort-handbooks-wide.jpg",
    "width": 2400,
    "height": 1807,
    "alt": "A Kids in Tech cohort holding their coding bootcamp handbooks with their instructor",
    "people": "children",
    "tag": "hero",
    "kb": 476,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAwAA4BaJYwAAoa0lUeAAP7JQWrM0try4HXFVR50ZKIuJHH1io6EZIRuPUJ3lbQQ7jbeG13dMt0fxKbzzkEnO+gu4YAIW70sQAAA"
  },
  {
    "file": "/images/groups/cohort-handbooks-close.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "Kids in Tech students showing their handbooks at the end of a bootcamp",
    "people": "children",
    "tag": "group",
    "kb": 286,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABQAgCdASoQAAwAA4BaJZQBTAHhARFU252o4AAA/tYR7kbNm6MsYkUPKm17K0Q1sDU9m0io7PfK2gzINwPjjKCehEQey8YNKOq9aiOZ4tMwDMEDJq4AAA=="
  },
  {
    "file": "/images/groups/cohort-kebbi-outdoor.jpg",
    "width": 1800,
    "height": 1350,
    "alt": "A Kids in Tech cohort gathered outside the training block",
    "people": "children",
    "tag": "group",
    "kb": 394,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAwAA4BaJZACdH8AGBsCyEK0yAD9UA5sLP7KwzkxSC1GiCrJlycfW+hYZJf2GCGCcmMM5oiYkdOgLzUlBdghH3ldd80wk7G9wqLBNu58o/QeNP4wZmG8mOkeAA=="
  },
  {
    "file": "/images/groups/cohort-celebration.jpg",
    "width": 1280,
    "height": 960,
    "alt": "Students, parents and the StarNova team together after a Kids in Tech session",
    "people": "children",
    "tag": "group",
    "kb": 165,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAwAA4BaJQBOgB7HGPJHc2OAAOAPNrAT4hsmj6vZLySP166W/1O7SXzOmVkQFQ6S6XEH1FmCu59sfW0gaowLcOW2Yw5z4D3TrMEcngQN4zjCGDAAAA=="
  },
  {
    "file": "/images/groups/cohort-families.jpg",
    "width": 1280,
    "height": 960,
    "alt": "Kids in Tech students and families at a graduation gathering",
    "people": "children",
    "tag": "group",
    "kb": 175,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwAA4BaJYwCdADLx2XsXTwAAOAPPlSDCjqGEL0Irfgo5wq65dYp7h2ze2sTRCk9ZLc/nSCC2nlDXG3GsUcsfTqe+DqT+DfQQ1fDQswRyeBA3jKI+AwA"
  },
  {
    "file": "/images/groups/parents-and-team.jpg",
    "width": 1280,
    "height": 960,
    "alt": "Parents and the StarNova Labs team at a Kids in Tech gathering",
    "people": "adults",
    "tag": "community",
    "kb": 166,
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAQCdASoQAAwAA4BaJQBOgBl3oPJvQgAA+kgwrVRctoMzx5XfMhRMpdS+oeNfIZ2q18AUqp9b7cC6CoWpMjk/vVzjz3T6em/ZQjep7yd672b9p7Zey/klJQPlPV0VKkayP2ijxtoYPIAA"
  },
  {
    "file": "/images/groups/cohort-classroom.jpg",
    "width": 1800,
    "height": 1350,
    "alt": "A Kids in Tech cohort standing together in the classroom",
    "people": "children",
    "tag": "group",
    "kb": 236,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAwAA4BaJQBOgCHXfuI9yAD+1RPwW5A15U4wZtc2SPqZNPQ/hpWNCcJh+9HJOzZIZU9JbY6ele1Ztn7nS0NMSJPNBOxSswvdY/KJPLhhiBAA"
  },
  {
    "file": "/images/groups/cohort-stairs.jpg",
    "width": 1350,
    "height": 1800,
    "alt": "Students holding their handbooks on the stairs of the learning centre",
    "people": "children",
    "tag": "group",
    "kb": 333,
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYgC7AB8jYww3jiUNELvAAP6yCWEeCPMzn3lL6WwXUjOCeOzkFpxv79g8swnnSq260Io3bDOxfPgik4IkIsng6YLsvBYXA/qrJa10XhOhpWd2E/7wF8fnivjTFw+BwMapUv+yr8PzOgku/DWu9aZAAAA="
  },
  {
    "file": "/images/classroom/instructor-teaching.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "An instructor walking the class through a lesson on the projector",
    "people": "children",
    "tag": "classroom",
    "kb": 281,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAwAA4BaJQBYdh4bUQkVFCwwAP34bH55S6cjg6GO71QrcqhZs5xrttF8akqHt1J3YKbU1lkmBOrMHE3I9aNmi6wUpK8eGF/WoAAA"
  },
  {
    "file": "/images/classroom/full-class-wide.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "A full Kids in Tech class at work on laptops",
    "people": "children",
    "tag": "classroom",
    "kb": 314,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAwAA4BaJagCdAEfvuxJWTSJ2AD87urG+P7qqQHWhoj8lc7XBUFPZNuhA85K+kMfvKfKDOkFRRT2Wz+trxbo5blepEoN6IWakm/r7OKjyRgA"
  },
  {
    "file": "/images/classroom/class-in-session.jpg",
    "width": 1800,
    "height": 1350,
    "alt": "A class in session in the Kids in Tech learning space",
    "people": "children",
    "tag": "classroom",
    "kb": 343,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAwAA4BaJZACdAEO68okiO7wAP6yOX6lDZgSI6CGDEEb5DOs9iIPoiyiabNJiZ2mj1cEKhSMVxrW3EfWZA7P5Mwkhuedn799Ro7wQjsbwAAA"
  },
  {
    "file": "/images/classroom/room-wide-1.jpg",
    "width": 1800,
    "height": 1350,
    "alt": "The Kids in Tech classroom full of students and laptops",
    "people": "children",
    "tag": "classroom",
    "kb": 328,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAwAA4BaJaACdAEQJxD0d4AA/pgRYUMeYafIdzhi+0hcKL+qIAI6IJOZBZ4tQ2ZM3jb6t+E6dZ7v81S2hNMp5Mgumf3Ae10+KnqB6nEnZwAA"
  },
  {
    "file": "/images/classroom/room-wide-2.jpg",
    "width": 1800,
    "height": 1350,
    "alt": "Students coding in the colourful Kids in Tech room",
    "people": "children",
    "tag": "classroom",
    "kb": 379,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoQAAwAA4BaJZgCdAYuREW7i11kgADyXya8WD7oR18Rdj8Ec8l5vnqXLXuzZzy7gQ/dwbYVP0uymfP23cE2nXWxE4S42hyTqo2YFYyLO/oZ1ykiVTkGvRwEG3pdtUAA"
  },
  {
    "file": "/images/classroom/projector-lesson.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "A lesson projected at the front of the class",
    "people": "children",
    "tag": "classroom",
    "kb": 269,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAwAA4BaJQBOgB8xR90SMAD+TNAq5iBar+4TMQ1N/toLikmHPcb7w7TstHPkrml+q3tXn7ws4DWCLUd4srcYmzMa4pUvFZzhjAUAAAA="
  },
  {
    "file": "/images/classroom/room-wide-3.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "Students working in pairs across the classroom",
    "people": "children",
    "tag": "classroom",
    "kb": 257,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwAgCdASoQAAwAA4BaJYgCdIMgFe/5e/JBe1qAAP7hxGjoF+5ZmaNoVkkXrJh2phWNoi9nLX32mXugxreuBFfR/EMDz/EePl+tKdcrn03wsX1oQLIe1KZqiTV97gAA"
  },
  {
    "file": "/images/classroom/instructor-helping.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "An instructor helping a student at her laptop",
    "people": "children",
    "tag": "classroom",
    "kb": 357,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAwAA4BaJbACdAD2OjcE6KQAAP3iWuK1WMHfhKBmasaB8TnDYGDNvvRM5O++mIOsH35v/xhVKVXY2qOY/WzgZ8vjBO08Hvt9roTW+vOo7egjQCAAAA=="
  },
  {
    "file": "/images/classroom/coding-and-chess.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "Students coding and playing chess during a session break",
    "people": "children",
    "tag": "classroom",
    "kb": 357,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQAgCdASoQAAwAA4BaJagCdADLnDZN1O4AAP34QQOaE3oMvc/DPaF+aNnEUH2m6psSo3KTWCdyGdWjw1/kyZasQB4alIXyO7v66+wL74dz9XNMheZx7woEUgV+PHZlC9NckniAAAA="
  },
  {
    "file": "/images/classroom/demo-day.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "Students watching a classmate present their project",
    "people": "children",
    "tag": "classroom",
    "kb": 291,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABwAgCdASoQAAwAA4BaJQBOmT+AsoLPSPc3FCMAAPa5TOgWq+49ACbm4wJm+30d3u6vqshmyQshnTK1vmgLJisxAP2MlG5OX0T9oCSIm8D/HyOBRwQYAAAA"
  },
  {
    "file": "/images/classroom/instructors-together.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "Two instructors preparing the next exercise",
    "people": "adults",
    "tag": "team",
    "kb": 244,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAwAA4BaJYwAD5UMU9O0OAAA/sil1qTQsDCxVT8dvx1PG5WdOFNRiSoaalsvR7l+s3/LltGhCJb5mxnF2gipFL+XDbEpc+nuSlpu2WvyvLPzx2AAAA=="
  },
  {
    "file": "/images/classroom/instructor-bw.jpg",
    "width": 1350,
    "height": 1800,
    "alt": "An instructor leading a session, black and white",
    "people": "adults",
    "tag": "team",
    "kb": 303,
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JaQAD5PoE2Q1+zaTq5Px5t4cAAM1whDmONP1IpW+P9ViNq6RhNl8StiuYDZgLiCeoUIcrQ0tguvTY50TWanQ1/VVFr6Zlicq+50cTZdh7q9iaJV2WVdTzK4EWd20QeoNLTXP6RZz8fAd7a+tuCEp92cPAnCs+3hUAAAAA"
  },
  {
    "file": "/images/coding/mentor-at-laptop.jpg",
    "width": 1355,
    "height": 1800,
    "alt": "A mentor guiding a student through her code",
    "people": "children",
    "tag": "coding",
    "kb": 262,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBXDgzAzGDPiOs9p9dy4JNYAAPzf6f6WeYh5M0gXNYf8xm0xsTzLSd34n63RiWkXRgvjqGqAymy1jDSezITDp8x+p0xTwBjyTxnWHz4l/xJD+b3KhM/6AEDrBpykByYhsJWtjr8PcXWU3TmF+AAA"
  },
  {
    "file": "/images/coding/over-shoulder-1.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "Students following the lesson on their own laptops",
    "people": "children",
    "tag": "coding",
    "kb": 211,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAwAA4BaJQBOgCHljwtdYoaAAP7yemwq9PvPqz+8QnVdn2jjHXTGHKbHtCB5rC4JnTs356J4QE0te2PYVt93VkGXI8M0ThtsJln8gAA="
  },
  {
    "file": "/images/coding/code-editor.jpg",
    "width": 1355,
    "height": 1800,
    "alt": "A student writing code in the editor",
    "people": "children",
    "tag": "coding",
    "kb": 253,
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JbACo9BmVrTTX25AQAPkSsHLL77ijq9zDH1TaAgrBc2HY3YTdn8wCdmmIL1TcmYabBRQHeqF/NO9KGuActAdbuIWfkPBZP/pwIE4s/wAr+iBUk0D/vJT6ZqZtylBRqKrsX3RaK3gfXzMEdF/mkzqf8YG0fyZjGcAAAA=="
  },
  {
    "file": "/images/coding/pair-coding.jpg",
    "width": 1800,
    "height": 1350,
    "alt": "Two students coding side by side",
    "people": "children",
    "tag": "coding",
    "kb": 310,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwAgCdASoQAAwAA4BaJbACdAdwB5oSNVpY869IAP7fylhfHvs3H9sNwfko9+yHyiMbzGpsubpP2cLt90cTm79cdsj53rFbJ2bvUBeJ0qtO/MK6hHdD0exE9/R9fTCYrAofx9+AAAA="
  },
  {
    "file": "/images/coding/student-laptop.jpg",
    "width": 1800,
    "height": 1350,
    "alt": "A student working through an exercise",
    "people": "children",
    "tag": "coding",
    "kb": 288,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQAAwAA4BaJbACdAEQUNBLIv9H/AAA/uqY/T2Y/chYdmWWlXbQE7dZJX2dJqj6wJxrY8rtaowPBhJg8J4lzN+hBosh0bGRxEz9vcFPnui54FC2855dFSXxAa7AAA=="
  },
  {
    "file": "/images/coding/laptop-closeup.jpg",
    "width": 1800,
    "height": 1350,
    "alt": "A laptop open on a web development exercise",
    "people": "none",
    "tag": "coding",
    "kb": 268,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAwAA4BaJbACdAEPhorz6VX5AAD+3r22hlHRmIt8x7Ad+gLniqnO3jdT6XAA2/mTMALvmgm4kn9gINAyFNUK1VQ1foVvM76E+J/gAAA="
  },
  {
    "file": "/images/coding/three-at-laptops.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "Three students coding together",
    "people": "children",
    "tag": "coding",
    "kb": 266,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQAQCdASoQAAwAA4BaJbACdACznJUEwAD+495eZjjma/YvP0p+pdubOjn2Pum79l7IIDsz1L6Nq/kQVWwwsuUxYFa8YweYLZBZ7sjDg6xG/QDEuP9iqsa99GMi8G8O1fLVzYgFJ5/Z0278otIAAA=="
  },
  {
    "file": "/images/coding/girls-coding.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "Students coding together under the Success wall",
    "people": "children",
    "tag": "coding",
    "kb": 301,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQAgCdASoQAAwAA4BaJbACdADpIoLp0hQAAP7gvZPSnlWmaC+u6Qjxydhn0zyz+xi93NLFs3IreX3m5xzFR12Yi9S4AdXet6woGJPVsOfWX9MuwDPOVbIJF+bnzYpd7CnNH30gAAA="
  },
  {
    "file": "/images/coding/laptop-success-wall.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "A student's laptop in front of the Kids in Tech wall art",
    "people": "children",
    "tag": "coding",
    "kb": 320,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAwAA4BaJbACdADdZbvMV8vgAP7qqUQCRZaEFoKqSRezbCvf7wP2Y6M3jesy+hy/FvIGWHW2T3AdqGbRhYWI98i0I/VoJN1xkf32dkEsYKcwZEHOjZJwAAA="
  },
  {
    "file": "/images/coding/hands-on-keyboard.jpg",
    "width": 1355,
    "height": 1800,
    "alt": "Hands on the keyboard during a web development lesson",
    "people": "children",
    "tag": "coding",
    "kb": 317,
    "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBWABDWBpKXwrmgaPNAKgAD+7UODC1KfgVr7PYX/LSvb7oH4CtA2ZNrrSUmE1hp3exndQIVkFGDwDTO+/1hgeYwGy5hLQYFJD9+Tk4jLBx7E6XI2hxXP9/l9vCnLt1yx06VEDoLdR2weRhFtMFtyARGddcZUzTBH9gXx5T2cAA=="
  },
  {
    "file": "/images/projects/scratch-game.jpg",
    "width": 1355,
    "height": 1800,
    "alt": "A student building a game in Scratch",
    "people": "children",
    "tag": "project-scratch",
    "kb": 286,
    "blurDataURL": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JagCdAB0hmy7ULhT/Y2AA33+nkMYaHtLeuCVKZGD3dgvVcCDh+d+hwfY61yOIWyXIxtrKU4wmuKUwPcs5kGHzZxwhZbUSoewWNHr+34zq90UkpMF/pAS27j6ANCLNeh6/0VXvcfFno0kHHUloIdexzyBaF5GZWq0M7FEEHTFZTmHAAAA="
  },
  {
    "file": "/images/projects/robotics-arduino.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "An Arduino robotics build wired to a laptop",
    "people": "none",
    "tag": "project-robotics",
    "kb": 261,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQAAwAA4BaJZACdACzYl00h7AA/vSo6lplS9KId5b3Qf5s0cwuD33tJoo5vSafjXMEgTdIg53c46SEsPvja2POo0k5J9uSZUNyPxiFZJhQys33q0xCo1xBcQAAAA=="
  },
  {
    "file": "/images/projects/scratch-on-laptop.jpg",
    "width": 1355,
    "height": 1800,
    "alt": "A Scratch project open on a student's laptop",
    "people": "none",
    "tag": "project-scratch",
    "kb": 280,
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdACal4AcuiTxJ0pndWn9SAAD81XhQrKAnb+SYKbVDD2U7o4BEKLeqHb/fZzYH398T0f68ZF5M2yyVk7t/9QOCX1764cq9jzjm4w4lRS9YRY/U7TLamlL9X2gGr9Baf/HuNKjZ5LYL0dWueOtGcVIlav43uTNAAA=="
  },
  {
    "file": "/images/projects/bootcamp-handbooks.jpg",
    "width": 1800,
    "height": 1355,
    "alt": "The Kids in Tech Coding Bootcamp handbooks",
    "people": "none",
    "tag": "product",
    "kb": 346,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQAgCdASoQAAwAA4BaJYwC7AEfbpxr/YF/zgAA/u6tnulcmQdgJjBMbKsLI+tvkObLVZjMBxEfFq5ds0hVyRESaAZqiugm+KRD8XfDH/mU9qZ4n74HcmzfDjmkKsAA"
  },
  {
    "file": "/images/team/aliyu-mubarak.jpg",
    "width": 1352,
    "height": 1800,
    "alt": "Aliyu Mubarak, Founder & CEO",
    "people": "adults",
    "tag": "team",
    "kb": 133,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoAC/J7s7wTAoN7vqSQA/silqZaB1QnxEte6CjCH5vWv/pwuJYVavdGF4esZVyGiVl2CmFjG7zyVAxB5RlwCw0yuU5S/yONM7I7WemEydXL/XdpPEMFfnTgTbEjcd1AA"
  },
  {
    "file": "/images/team/founder-handbook.jpg",
    "width": 1355,
    "height": 1800,
    "alt": "Aliyu Mubarak, Founder & CEO",
    "people": "adults",
    "tag": "team",
    "kb": 252,
    "blurDataURL": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoMYHYAASWISy9nnoDqmAAD8WkoUO/StyQg1iHfi5EZnFEmPV1ASf/6z4bl1mtVGjP4obCEqRh/qe38W+INqbCzRwrNbhXXnMKJBr24FNe045HdBvkQUkXFGk/6mZCVZyEgaqQdR6Exh7vTB0+hqi2CyykSZWDVXacpj3Cz+AAA="
  },
  {
    "file": "/images/community/foosball.jpg",
    "width": 1350,
    "height": 1800,
    "alt": "Students playing table football during a break",
    "people": "children",
    "tag": "community",
    "kb": 313,
    "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQC7AB9HtvSc7Q1HRlnbAAD5Z3OnvqsMcNPqzq4Q5eRIcS2So9Ip/aDh5lCo4r1BCssvdN0it1O6PNF9Xfc2G4OXPHSuakYtJvBq39Xjafu/8lLdwK2Y0li89WSmrKHK92pgj2N9f+2JRBmNYWQETbDepV7Dt7M7kiASAAA="
  },
  {
    "file": "/images/community/chess-with-mentor.jpg",
    "width": 1350,
    "height": 1800,
    "alt": "A mentor playing chess with a student",
    "people": "children",
    "tag": "community",
    "kb": 467,
    "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAACQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoR4GCfn7LCVtE/oGQ8e4KAA/O45vlBAYRYbkCMYHjAo2IRi01PwC5I5ksgfEyH+WWh3QUfpJNQeuD248qI5p4Avc76lAz4+fWh548hDMBmfoetMVY1Zc2mskZ8zH6xmI+Ldj+3VbUSXOR8rD/PpHyLPs/iWK70QQ2x1cMSPUw/y1QgAAAA="
  },
  {
    "file": "/images/community/board-games.jpg",
    "width": 1350,
    "height": 1800,
    "alt": "Students playing a board game together",
    "people": "children",
    "tag": "community",
    "kb": 317,
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdAYxstr2qPvtvnoJQG5AA96eVxRJGWRBfWW+k+z5lY1ozn4OW80tB+tNfJ/dQhqTP6+E8SW59FkjpYEkyhJb31ovsTUfMrh9vSxLE2T3auEgavc845TsC56n29Som5x33+ArFENbDxn8WVNYCbje5H7ZmriLf7d/FyWQ3X4z73ZELcAAA"
  },
  {
    "file": "/images/community/break-time.jpg",
    "width": 1350,
    "height": 1800,
    "alt": "Students relaxing during a break",
    "people": "children",
    "tag": "community",
    "kb": 355,
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoQABUAPu1iqU2ppaQiMAgBMB2JbAC21iAAJQKCl3v1OkzmD7IAAPjxppN2kzBG1AAf6rynsGtxEVRHCqezgk8XlKfZ7BLblqDn0/33DlQpg0bJUeVTGjYEpHt2WQZrXvONRbMpLSFgdMTlDVgwzDcqj4yya08ttsGS5J18E5ibwUigFxVgTYAA"
  },
  {
    "file": "/images/community/chess-match.jpg",
    "width": 1355,
    "height": 1800,
    "alt": "Students playing chess",
    "people": "children",
    "tag": "community",
    "kb": 369,
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBACdASoQABUAPu1kqU2ppaOiMAgBMB2JYgC2yCPp1etiYwdqVLjpOoAA/tX78VpLhYbQY3rRRogt/ad9YtMVfacKPIKIugc4On2UclFxNi8RbJgAzzRnDUgVe6ymDen/LadmyesvqmO2UB/ek6tnYid2qTDzYMXqnRl3dKUQz4eC7n2vqyirNev7y1xqiAAAAA=="
  },
  {
    "file": "/images/community/jenga.jpg",
    "width": 1350,
    "height": 1800,
    "alt": "Students playing Jenga at Bootcamp 2.0",
    "people": "children",
    "tag": "community",
    "kb": 293,
    "blurDataURL": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoRwACT21UluqUI4dBnh+EAA/shyb6llQcOoep+kqnTr7+33mIYRYbzVowOSqVrUL2sLca1epWOsGq/UpzTK6dCruywi/i+CsvC72X9X76D+qaFtTdVvCJVwX058sELtRg8vZYDC7OdVaZq0YiVi3rfHWU5zNkthMxAawwvgAAA="
  },
  {
    "file": "/images/community/chess-bootcamp2.jpg",
    "width": 1350,
    "height": 1800,
    "alt": "Students playing chess at Bootcamp 2.0",
    "people": "children",
    "tag": "community",
    "kb": 367,
    "blurDataURL": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAADwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZACdMoR3AdCVD7Pjla1lI4sXlqCYrQAA/udWENPhL8Faf87bliv/PGhwJlhil7+HxVIFWmKTK4qn5Bmt6wBSTIgHOQM9496uGB7mjIPKaGITe7vOjcNfjHxiWJpn3yOjczAeWwSVxf/duR15SgQAauBbL7t9qW+fndXFaQspzn5A/zOCJHjwuL/hLgUoaAAAAA=="
  },
  {
    "file": "/images/team/aisha-zakari.jpg",
    "width": 1108,
    "height": 1385,
    "alt": "Portrait of Aisha Zakari",
    "people": "adults",
    "tag": "team",
    "kb": 130,
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JQBadMY2UB8+Na95L8RhiogAA/vNJ52vMMPJHIqEc7QIQoELayIVDFp7i0SpaByx9oUFV1KyFFidVD033E6UR/8+/5CNA+ibWCm5ot/kjuef7BpX9o+kCZb2nHQUisRATht+Ko4cytEpaQiC/3uEv87X/QhLaALAAAA=="
  },
  {
    "file": "/images/team/faruk-yusuf.jpg",
    "width": 688,
    "height": 860,
    "alt": "Portrait of Faruk Yusuf",
    "people": "adults",
    "tag": "team",
    "kb": 53,
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JbACdMoMYOEAAglEKv6NSUg4ENgAA/sOhJw1LvnhHWDjXTr92RpNCgjQCPab6rLmDJ1WqvZ3NRmNVW5GGRdCR4X5CxDFtFul8+dd9qT5P3mfUsJAFh9tXua3h76iXcCjkCxIyowaDgE1dD9H9NyPSXYe1LGgciE9AAA=="
  },
  {
    "file": "/images/team/mustapher.jpg",
    "width": 577,
    "height": 607,
    "alt": "Mustapher M. Lawal, Co-Founder & CTO",
    "people": "adults",
    "tag": "team",
    "kb": 46,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoQABEAPu1iqU2ppaOiMAgBMB2JaQAAXy6AGLq+OkP0H6KY0ADOPT+J6N5xnoxF8MNZHW98o3fa3rRmfTyW5i/I4cyT2A/2stpx7RD7P+T+TbsFg1KkdKZ0XUONUygDSBUJ7L9Z9tthvbB2aMs3P/ee/4WKAAAA"
  },
  {
    "file": "/images/kitos/kitos-1.png",
    "width": 1431,
    "height": 1180,
    "alt": "KITOS sign-in screen",
    "people": "none",
    "tag": "kitos",
    "kb": 0,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoQAA0AA4BaJZwAAtz95mbJ4QAA/vfqTiP4SxuvZLPV2h4Bd42fkvn1A8SLK+khtZX3AAAA"
  },
  {
    "file": "/images/kitos/kitos-2.png",
    "width": 1429,
    "height": 1197,
    "alt": "KITOS student dashboard",
    "people": "none",
    "tag": "kitos",
    "kb": 0,
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoQAA0AA4BaJaQAAtzhcAAAAP72QRabEfTgDJf2iTzdYD9ocyq5uAAA"
  },
  {
    "file": "/images/kitos/kitos-6.png",
    "width": 1427,
    "height": 1040,
    "alt": "KITOS online classes",
    "people": "none",
    "tag": "kitos",
    "kb": 0,
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoQAAwAA4BaJaQAAt0OFa7MgAAA/vcS/a16Hzi+kN/tAvu1VcBAAAAA"
  },
  {
    "file": "/images/kitos/kitos-7.png",
    "width": 1436,
    "height": 1047,
    "alt": "KITOS session recordings",
    "people": "none",
    "tag": "kitos",
    "kb": 0,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAwAA4BaJaQAD4SQke8tWAAA/vZGtSJ4qDpOvag56e2jVNf42ShkPgnE59UhV1Nx6ieFMYW4Bx1fYs1OtPWapMJmFAAA"
  },
  {
    "file": "/images/kitos/kitos-22.png",
    "width": 1431,
    "height": 1053,
    "alt": "KITOS lesson view",
    "people": "none",
    "tag": "kitos",
    "kb": 0,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAwAA4BaJZQAAuyhb4w2AAD+8oza929/PdPyN3FE3DR+k0snfaBLooE4RitLkjm8QFjcn6Aq7ZHNkn+lIb8bJFg6ZMVwAAA="
  },
  {
    "file": "/images/kitos/kitos-27.png",
    "width": 1436,
    "height": 1049,
    "alt": "KITOS admin dashboard",
    "people": "none",
    "tag": "kitos",
    "kb": 0,
    "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACQAQCdASoQAAwAA4BaJZwAAudFrAAA/vcKVMX3eP6z/0bfKzKo49RkTy0AAA=="
  },
  {
    "file": "/images/kitos/kitos-31.png",
    "width": 1434,
    "height": 1048,
    "alt": "KITOS live sessions overview",
    "people": "none",
    "tag": "kitos",
    "kb": 0,
    "blurDataURL": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACQAQCdASoQAAwAA4BaJaQAAud7sAAA/vcKTGWJY3xiZPiAAAA="
  },
  {
    "file": "/images/kitos/kitos-32.png",
    "width": 1431,
    "height": 1047,
    "alt": "KITOS attendance reports",
    "people": "none",
    "tag": "kitos",
    "kb": 0,
    "blurDataURL": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAAAwAQCdASoQAAwAA4BaJaQAA3AA/vRHzAVOpMBc9koD34oQAAA="
  },
  {
    "file": "/images/kitos/kitos-33.png",
    "width": 1429,
    "height": 1045,
    "alt": "KITOS recordings management",
    "people": "none",
    "tag": "kitos",
    "kb": 0,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAwAA4BaJZwAD4wQb6dkQAD+9xL9pzitjxsthkN6HOfVMVrwU82P3fC2K8Kt831WYNVlFjKwcAAA"
  },
  {
    "file": "/images/kitos/kitos-34.png",
    "width": 1430,
    "height": 1044,
    "alt": "KITOS analytics and insights",
    "people": "none",
    "tag": "kitos",
    "kb": 0,
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoQAAwAA4BaJZwAAuWs5kAAAP73Ey1lox3AuMmUwH1ql+YzwZktypalTafKcsAA"
  },
  {
    "file": "/video/kit-classroom-loop.mp4",
    "width": 720,
    "height": 1280,
    "alt": "Kids in Tech classes in session",
    "people": "children",
    "tag": "video",
    "kb": 0,
    "blurDataURL": null
  },
  {
    "file": "/video/scratch-game-loop.mp4",
    "width": 720,
    "height": 1280,
    "alt": "A student playing the Scratch game they built",
    "people": "children",
    "tag": "video",
    "kb": 0,
    "blurDataURL": null
  },
  {
    "file": "/logos/partners/gdg-birnin-kebbi.png",
    "width": 900,
    "height": 366,
    "alt": "GDG Birnin-Kebbi",
    "people": "none",
    "tag": "logo",
    "kb": 36,
    "blurDataURL": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoQAAcAA4BaJaQAAuXJuEAA/vZKngECf0g7ix2VrdzfWjwAAAA="
  },
  {
    "file": "/logos/partners/hib-greenbox.png",
    "width": 900,
    "height": 236,
    "alt": "HiB Greenbox",
    "people": "none",
    "tag": "logo",
    "kb": 54,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4WAoAAAAQAAAADwAAAwAAQUxQSEEAAAAA6M/A5j9tXCGEPAAEAQICAbx7iaRQMkciUisAAgAAAADYb1jFRjIuHishJCw6HiUZ5s+/5T1WaW+MhHhlinl0fABWUDggJAAAAJABAJ0BKhAABAADgFoljAAC50/g4AD+8MrlUiSHVpf4xAAAAA=="
  },
  {
    "file": "/logos/partners/startup-kebbi-onLight.png",
    "width": 337,
    "height": 150,
    "alt": "Startup Kebbi",
    "people": "none",
    "tag": "logo",
    "kb": 15,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoQAAcAA4BaJZwAAp123IskAAD+9iHp2NlWkzG5N20Xr/RIGZVl5QHuLIFJfhwIAAA="
  },
  {
    "file": "/logos/partners/startup-kebbi-onDark.png",
    "width": 900,
    "height": 401,
    "alt": "Startup Kebbi",
    "people": "none",
    "tag": "logo",
    "kb": 67,
    "blurDataURL": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4WAoAAAAQAAAADwAABgAAQUxQSGMAAAABcGTbtuHcsqt6Fdu2rZZtJ62sDCDz1xgiYgKYgAf/6+UcDdD1TjU/6VUzR3vBBALMoTm+PpuDxzVSCCUNlDjvLfvXBEPBFWgk8pq43bwO7wIFklTKBokEQeInGycBEAQI4gMAVlA4IB4AAAAwAQCdASoQAAcAA4BaJaQAA3AA/vTn1lkwym48AAA="
  },
  {
    "file": "/logos/partners/starok-design-school.png",
    "width": 900,
    "height": 156,
    "alt": "Starok Design School",
    "people": "none",
    "tag": "logo",
    "kb": 99,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4WAoAAAAQAAAADwAAAgAAQUxQSDEAAAAAnrlYKj1ISlVIRgAAAAAAAf+tZlQ9TVZRXkQoJCcpKhc4o2UPRl1OUGA8VElTU1JGAFZQOCAaAAAAMAEAnQEqEAADAAOAWiWkAANwAP70YHUAAAA="
  },
  {
    "file": "/logos/products/nurala-onLight.png",
    "width": 900,
    "height": 402,
    "alt": "NurAla Learning",
    "people": "none",
    "tag": "logo",
    "kb": 211,
    "blurDataURL": "data:image/webp;base64,UklGRgIBAABXRUJQVlA4WAoAAAAQAAAADwAABgAAQUxQSHEAAAAAACmx4b87AAIABAsAAwQDAAvR//z/6RREX049NVhXSzxL//v9+f9hN3J3cmFkcXN+S//7/Pr/bAAUDxwWDxMWFA/L//v/3ychLig2NDAxMDEAK6jVtDwAAwEDAgEBAAICAAAGFgkAAQAAAAAAAAAAAABWUDggagAAADACAJ0BKhAABwADgFolsAJ0BivtrdpqdDsAAPwmakj+rmGoVz4keIEqfXgsCdRYkGRfVc9p9x8ezf1WfxF7phr3urGTYwOEKPir3rCvkhxZ+XPxTTZPgzMFVOfqEOxeVen8L+dImE3hEAA="
  },
  {
    "file": "/logos/products/nurala-onDark.png",
    "width": 900,
    "height": 401,
    "alt": "NurAla Learning",
    "people": "none",
    "tag": "logo",
    "kb": 220,
    "blurDataURL": "data:image/webp;base64,UklGRvAAAABXRUJQVlA4WAoAAAAQAAAADwAABgAAQUxQSGwAAAAFcBvbtqrc+wV3d4cSnApomR4cMneLXJ7djBoiIiFa0Wh2QLIYb4NAOto3pSLdTnDLPzkGp0zoHmVqX6zdnFfd4kbNm0NPj4185GBMN+W+Go4tXlOn4+clpkvzli5b+GKpKw0ICBHAbv++4Q9WUDggXgAAABACAJ0BKhAABwADgFolsAJ0BiwW9+N23EAA/PVxAjcmFRtj64uB8e4/j4Cr7UwB+MoLDYrKeyGsTXXC329uBWluk70negyKCB5DexX0HmZ7hZ2NW+k2Ayy6F1x8AAA="
  },
  {
    "file": "/logos/products/kids-in-tech.png",
    "width": 900,
    "height": 418,
    "alt": "Kids in Tech",
    "people": "none",
    "tag": "logo",
    "kb": 159,
    "blurDataURL": "data:image/webp;base64,UklGRvYAAABXRUJQVlA4WAoAAAAQAAAADwAABgAAQUxQSHEAAAAATZ7U4+v/n7XfjHEDAAMBAPT55P/i6v/+/v/9dRYDAgJDndTz7/r4/vj88frziB0AAQC1//XWkZGq3NPj5/+LCgQAVfT/+u3i+Pb/6If1/+kBAAXZ7vb///7/1Onry9uOAAEAaGF1kWibjWZ8s1MIAgBWUDggXgAAANABAJ0BKhAABwADgFolsAJ0AOF9HWUAAP6sUb1t1qE5TMFqqF88I9OuoS/Dz7CFcLRyBd0z4TNXmJqBbjyNxPfK2dFd2cAiJXTmdwz2N0rjgcejlv72emKHKnfEgAA="
  },
  {
    "file": "/images/edustack/edustack-home.png",
    "width": 1440,
    "height": 900,
    "alt": "The EduStack demo landing page",
    "people": "none",
    "tag": "edustack",
    "kb": 134,
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAABwAQCdASoQAAoAA4BaJYwCdAFAAAD+76CHdJamg7Dq7TjW5ZO6evGfPGPNIg6ZYAA="
  },
  {
    "file": "/images/edustack/edustack-mobile.png",
    "width": 390,
    "height": 844,
    "alt": "The EduStack demo on a phone",
    "people": "none",
    "tag": "edustack",
    "kb": 99,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwBACdASoQACMAPt1apE2opSOiNUgBEBuJZwDMHC+/2P/Jofwrj21nGAAA/tmqq0fptOTvIZXCf1bxoQtoFi+NuHc9eo6/Y0Hei99WlOL+xjk5k0eVDLjkuA/C3r5Tr7i6+3Djc4AAAA=="
  }
];
