/**
 * Turns docs/assets/image-manifest.json into a typed module, adding a tiny
 * base64 blur placeholder per image so next/image can render one without a
 * round trip. Run with `npm run build:images` after changing the manifest.
 */
const fs = require('node:fs');
const path = require('node:path');
const sharp = require('sharp');

const ROOT = process.cwd();
const MANIFEST = path.join(ROOT, 'docs/assets/image-manifest.json');
const OUT = path.join(ROOT, 'src/content/images.generated.ts');

function readManifest() {
  const raw = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  return Array.isArray(raw) ? raw : (raw.images ?? raw.assets ?? []);
}

async function blurFor(file) {
  const onDisk = path.join(ROOT, 'public', file.replace(/^\//, ''));
  if (!fs.existsSync(onDisk)) return null;
  // 16px wide is enough to suggest the colours and costs ~1 KB of base64.
  const buffer = await sharp(onDisk).resize(16).webp({ quality: 40 }).toBuffer();
  return `data:image/webp;base64,${buffer.toString('base64')}`;
}

async function main() {
  const entries = readManifest();
  const rows = [];
  const missing = [];

  for (const entry of entries) {
    const file = entry.file ?? entry.src;
    if (!file) continue;

    const isVideo = /\.(mp4|webm)$/i.test(file);
    const blur = isVideo ? null : await blurFor(file);
    if (!isVideo && !blur) missing.push(file);

    rows.push({
      file,
      width: entry.width ?? 0,
      height: entry.height ?? 0,
      alt: entry.alt ?? '',
      people: entry.people ?? 'none',
      tag: entry.tag ?? 'none',
      kb: entry.kb ?? 0,
      blurDataURL: blur,
    });
  }

  const body = `// Generated by scripts/build-images.cjs — do not edit by hand.
// Source of truth: docs/assets/image-manifest.json
// Regenerate with: npm run build:images

import type { ImageAsset } from '@/content/images';

export const GENERATED_IMAGES: ImageAsset[] = ${JSON.stringify(rows, null, 2)};
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);

  console.log(`images: wrote ${rows.length} entries to ${path.relative(ROOT, OUT)}`);
  if (missing.length) {
    console.warn(`images: ${missing.length} file(s) missing on disk:`);
    missing.forEach((f) => console.warn(`  ${f}`));
    process.exitCode = 1;
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
